import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { X, ChevronDown, Plus, Upload, Trash2 } from 'lucide-react';
import api from '../../api';
import { PopupAnimation, useAnimationState } from '../../utils/AnimationUtils';
import { useNotification } from '../../components/Notifications';

interface Product {
  id: number;
  name?: string;
  product_name?: string;
  price?: string;
  base_price?: string;
  bdt_price?: number;
}

interface Client {
  id: number;
  company: string;
  contact: string;
}

interface SelectedProduct {
  productId: number;
  productName: string;
  quantity: number;
}

interface CreatePurchaseOrderPopupProps {
  isOpen: boolean;
  onClose: () => void;
  onCreate: (orderData: any) => void;
}

const CreatePurchaseOrderPopup: React.FC<CreatePurchaseOrderPopupProps> = ({
  isOpen,
  onClose,
  onCreate,
}) => {
  const { showError, showInfo } = useNotification();

  const [formData, setFormData] = useState({
    poNumber: '',
    status: 'Draft',
    client: '',
    clientId: 0,
    subscriptionType: '',
    recurringCount: 1,
    deliveryDate: '',
    subscriptionActive: false,
    poDetails: '',
  });

  const [selectedProducts, setSelectedProducts] = useState<SelectedProduct[]>([]);
  const [currentProductId, setCurrentProductId] = useState<number>(0);
  const [currentQuantity, setCurrentQuantity] = useState<number>(1);

  const [dropdownOpen, setDropdownOpen] = useState({
    status: false,
    client: false,
    product: false,
    subscriptionType: false,
  });

  const [loading, setLoading] = useState(false);
  const [poNumberLoading, setPoNumberLoading] = useState(false);
  const [clients, setClients] = useState<Client[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [attachments, setAttachments] = useState<File[]>([]);

  const statusOptions = ['Draft', 'Active', 'In Progress', 'Completed'];

  useEffect(() => {
    if (isOpen) {
      fetchData();
      setSelectedProducts([]);
      setAttachments([]);
      setCurrentProductId(0);
      setCurrentQuantity(1);
      setFormData(prev => ({
        ...prev,
        subscriptionActive: false,
        subscriptionType: '',
        recurringCount: 1,
        deliveryDate: '',
        poDetails: '',
      }));
    }
  }, [isOpen]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [clientsRes, productsRes] = await Promise.all([
        api.get('/clients'),
        api.get('/products')
      ]);
      setClients(clientsRes.data || []);
      setProducts(productsRes.data || []);
      fetchAutoGeneratedPoNumber();
    } catch (error) {
      console.error('Error fetching data:', error);
      showError('Failed to load data');
    } finally {
      setLoading(false);
    }
  };

  const fetchAutoGeneratedPoNumber = async () => {
    setPoNumberLoading(true);
    try {
      const res = await api.get('/purchases/generate-po');
      if (res.data?.po_number) {
        setFormData(prev => ({ ...prev, poNumber: res.data.po_number }));
      }
    } catch (error) {
      const year = new Date().getFullYear();
      setFormData(prev => ({ ...prev, poNumber: `PO-${year}-0001` }));
    } finally {
      setPoNumberLoading(false);
    }
  };

  const toggleDropdown = (key: keyof typeof dropdownOpen) => {
    setDropdownOpen(prev => ({
      ...prev,
      [key]: !prev[key],
      ...(key !== 'status' && { status: false }),
      ...(key !== 'client' && { client: false }),
      ...(key !== 'product' && { product: false }),
      ...(key !== 'subscriptionType' && { subscriptionType: false }),
    }));
  };

  const selectClient = (client: Client) => {
    setFormData(prev => ({
      ...prev,
      client: `${client.company}`,
      clientId: client.id
    }));
    toggleDropdown('client');
  };

  const selectStatus = (status: string) => {
    setFormData(prev => ({ ...prev, status }));
    toggleDropdown('status');
  };

  const addProduct = () => {
    if (currentProductId === 0) return showInfo('Please select a product');
    if (currentQuantity < 1) return showInfo('Quantity must be at least 1');

    const product = products.find(p => p.id === currentProductId);
    if (!product) return;

    const existingIndex = selectedProducts.findIndex(p => p.productId === currentProductId);
    if (existingIndex !== -1) {
      setSelectedProducts(prev => {
        const updated = [...prev];
        updated[existingIndex].quantity += currentQuantity;
        return updated;
      });
    } else {
      setSelectedProducts(prev => [...prev, {
        productId: currentProductId,
        productName: product.product_name || product.name || 'Unknown',
        quantity: currentQuantity
      }]);
    }

    setCurrentProductId(0);
    setCurrentQuantity(1);
    toggleDropdown('product');
  };

  const removeProduct = (index: number) => {
    setSelectedProducts(prev => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.clientId) return showInfo('Please select a client');
    if (selectedProducts.length === 0) return showInfo('Add at least one product');

    if (formData.subscriptionActive) {
      if (!formData.subscriptionType) return showInfo('Select subscription type');
      if (!formData.deliveryDate) return showInfo('Select delivery date');
      if (formData.recurringCount < 1) return showInfo('Recurring count must be ≥1');
    }

    const data = {
      po_number: formData.poNumber,
      status: formData.status,
      client_id: formData.clientId,
      products: selectedProducts.map(p => ({ productId: p.productId, quantity: p.quantity })),
      subscription_type: formData.subscriptionType ? formData.subscriptionType : null,
      recurring_count: formData.subscriptionType ? formData.recurringCount : null,
      delivery_date: formData.deliveryDate ? formData.deliveryDate : null,
      subscription_active: formData.subscriptionActive,
      po_details: formData.poDetails ? formData.poDetails : null,
      attachment: attachments[0] || null,
    };

    onCreate(data);
    onClose();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    const validFiles = files.filter(file => {
      if (file.size > 10 * 1024 * 1024) {
        showError(`${file.name} too large (max 10MB)`);
        return false;
      }
      return true;
    });
    setAttachments(validFiles.slice(0, 5));
  };

  const removeAttachment = (i: number) => {
    setAttachments(prev => prev.filter((_, idx) => idx !== i));
  };

  const formatFileSize = (bytes: number) => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  const { isVisible, isAnimating } = useAnimationState(isOpen);
  if (!isVisible) return null;

  return createPortal(
    <div
      className={`fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 px-4 transition-opacity duration-300 ${
        isAnimating ? 'opacity-100' : 'opacity-0'
      }`}
      onClick={onClose}
    >
      <PopupAnimation animationType="zoomIn" duration="0.3s">
        <div
          className="w-full max-w-3xl rounded-xl bg-white shadow-xl max-h-[95vh] overflow-hidden flex flex-col"
          onClick={e => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b border-gray-200 bg-gray-50 px-5 py-3">
            <h2 className="text-lg font-semibold text-gray-900">Create Purchase Order</h2>
            <button
              onClick={onClose}
              className="rounded-md p-1.5 text-gray-500 hover:bg-gray-200 hover:text-gray-700"
              aria-label="Close"
            >
              <X size={20} />
            </button>
          </div>

          {/* Scrollable Form Content */}
          <div className="overflow-y-auto flex-1">
            <form onSubmit={handleSubmit} className="space-y-5 p-5">
              {/* Basic Info */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">PO Number</label>
                  <input
                    type="text"
                    value={poNumberLoading ? 'Generating...' : formData.poNumber}
                    readOnly
                    className="w-full rounded-md border border-gray-300 bg-gray-50 px-3 py-2 text-sm"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
                  <div className="relative">
                    <button
                      type="button"
                      onClick={() => toggleDropdown('status')}
                      className="w-full flex justify-between items-center rounded-md border border-gray-300 px-3 py-2 text-sm bg-white"
                    >
                      {formData.status}
                      <ChevronDown size={16} />
                    </button>
                    {dropdownOpen.status && (
                      <div className="absolute z-10 mt-1 w-full rounded-md bg-white shadow-lg border">
                        {statusOptions.map(opt => (
                          <button
                            key={opt}
                            type="button"
                            onClick={() => selectStatus(opt)}
                            className="w-full px-3 py-2 text-left text-sm hover:bg-blue-50"
                          >
                            {opt}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Client</label>
                  <div className="relative">
                    <button
                      type="button"
                      onClick={() => toggleDropdown('client')}
                      className="w-full flex justify-between items-center rounded-md border border-gray-300 px-3 py-2 text-sm bg-white"
                    >
                      <span className={formData.client ? '' : 'text-gray-500'}>
                        {formData.client || 'Select client'}
                      </span>
                      <ChevronDown size={16} />
                    </button>
                    {dropdownOpen.client && (
                      <div className="absolute z-10 mt-1 w-full rounded-md bg-white shadow-lg border max-h-48 overflow-y-auto">
                        {loading ? (
                          <div className="px-3 py-2 text-sm text-gray-500">Loading...</div>
                        ) : (
                          clients.map(client => (
                            <button
                              key={client.id}
                              type="button"
                              onClick={() => selectClient(client)}
                              className="w-full px-3 py-2 text-left text-sm hover:bg-blue-50"
                            >
                              <div className="font-medium">{client.company}</div>
                              <div className="text-xs text-gray-500">{client.contact}</div>
                            </button>
                          ))
                        )}
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Add Product */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Products</label>
                <div className="grid grid-cols-1 md:grid-cols-12 gap-3 items-end">
                  <div className="md:col-span-7">
                    <div className="relative">
                      <button
                        type="button"
                        onClick={() => toggleDropdown('product')}
                        className="w-full flex justify-between items-center rounded-md border border-gray-300 px-3 py-2 text-sm bg-white"
                      >
                        <span className={currentProductId ? '' : 'text-gray-500'}>
                          {products.find(p => p.id === currentProductId)?.product_name ||
                           products.find(p => p.id === currentProductId)?.name ||
                           'Select product'}
                        </span>
                        <ChevronDown size={16} />
                      </button>
                      {dropdownOpen.product && (
                        <div className="absolute z-10 mt-1 w-full rounded-md bg-white shadow-lg border max-h-48 overflow-y-auto">
                          {products.map(p => (
                            <button
                              key={p.id}
                              type="button"
                              onClick={() => {
                                setCurrentProductId(p.id);
                                toggleDropdown('product');
                              }}
                              className="w-full px-3 py-2 text-left text-sm hover:bg-blue-50"
                            >
                              <div>{p.product_name || p.name}</div>
                              <div className="text-xs text-gray-500">৳{p.bdt_price || p.price}</div>
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="md:col-span-3">
                    <input
                      type="number"
                      min="1"
                      value={currentQuantity}
                      onChange={e => setCurrentQuantity(Math.max(1, parseInt(e.target.value) || 1))}
                      className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                      placeholder="Qty"
                    />
                  </div>

                  <div className="md:col-span-2">
                    <button
                      type="button"
                      onClick={addProduct}
                      className="w-full px-3 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 text-sm flex items-center justify-center gap-1"
                    >
                      <Plus size={16} /> Add
                    </button>
                  </div>
                </div>

                {/* Selected Products - Now Scrollable */}
                {selectedProducts.length > 0 && (
                  <div className="mt-4 border rounded-md">
                    <div className="bg-gray-50 px-3 py-2 text-sm font-medium border-b">
                      Selected Products ({selectedProducts.length})
                    </div>
                    <div className="max-h-52 overflow-y-auto"> {/* Scrollable area */}
                      {selectedProducts.map((item, i) => (
                        <div key={i} className="flex justify-between items-center px-3 py-2.5 border-b last:border-b-0 hover:bg-gray-50">
                          <div className="text-sm">
                            <div className="font-medium">{item.productName}</div>
                            <div className="text-gray-600">Quantity: {item.quantity}</div>
                          </div>
                          <button
                            type="button"
                            onClick={() => removeProduct(i)}
                            className="text-red-600 hover:text-red-800 p-1"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Subscription & Delivery */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <div>
                  <div className="flex items-center gap-3 mb-3">
                    <input
                      type="checkbox"
                      id="sub"
                      checked={formData.subscriptionActive}
                      onChange={e => setFormData(prev => ({ ...prev, subscriptionActive: e.target.checked }))}
                      className="h-4 w-4 rounded"
                    />
                    <label htmlFor="sub" className="text-sm font-medium">Subscription Active</label>
                  </div>

                  {formData.subscriptionActive && (
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Type</label>
                        <div className="relative">
                          <button
                            type="button"
                            onClick={() => toggleDropdown('subscriptionType')}
                            className="w-full flex justify-between items-center rounded-md border border-gray-300 px-3 py-2 text-sm bg-white"
                          >
                            {formData.subscriptionType ? `${formData.subscriptionType} mo` : 'Months'}
                            <ChevronDown size={14} />
                          </button>
                          {dropdownOpen.subscriptionType && (
                            <div className="absolute z-10 mt-1 w-full rounded-md bg-white shadow-lg border">
                              {[1, 2, 3, 6, 12].map(m => (
                                <button
                                  key={m}
                                  type="button"
                                  onClick={() => {
                                    setFormData(prev => ({ ...prev, subscriptionType: m.toString() }));
                                    toggleDropdown('subscriptionType');
                                  }}
                                  className="w-full px-3 py-2 text-left text-sm hover:bg-blue-50"
                                >
                                  {m} month{m > 1 ? 's' : ''}
                                </button>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>

                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Recurring</label>
                        <input
                          type="number"
                          min="1"
                          value={formData.recurringCount}
                          onChange={e => setFormData(prev => ({ ...prev, recurringCount: Math.max(1, parseInt(e.target.value) || 1) }))}
                          className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                        />
                      </div>
                    </div>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Delivery Date {formData.subscriptionActive && '(Required)'}
                  </label>
                  <input
                    type="date"
                    value={formData.deliveryDate}
                    onChange={e => setFormData(prev => ({ ...prev, deliveryDate: e.target.value }))}
                    className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                  />
                </div>
              </div>

              {/* Compact PO Details & Attachments */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">PO Details (Optional)</label>
                  <textarea
                    rows={3}
                    value={formData.poDetails}
                    onChange={e => setFormData(prev => ({ ...prev, poDetails: e.target.value }))}
                    className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm resize-none"
                    placeholder="Add notes or special instructions..."
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Attachments (Optional, max 5)</label>
                  <label className="block border-2 border-dashed border-gray-300 rounded-lg p-3 text-center cursor-pointer hover:border-gray-400 transition">
                    <Upload className="mx-auto text-gray-400 mb-1" size={24} />
                    <span className="text-sm text-blue-600 block">Click to upload</span>
                    <span className="text-xs text-gray-500">Max 10MB each</span>
                    <input type="file" multiple className="hidden" onChange={handleFileChange} />
                  </label>

                  {attachments.length > 0 && (
                    <div className="mt-3 space-y-2 max-h-32 overflow-y-auto">
                      {attachments.map((file, i) => (
                        <div key={i} className="flex justify-between items-center bg-gray-50 px-3 py-2 rounded text-sm">
                          <div className="flex-1 min-w-0">
                            <div className="font-medium truncate">{file.name}</div>
                            <div className="text-xs text-gray-500">{formatFileSize(file.size)}</div>
                          </div>
                          <button type="button" onClick={() => removeAttachment(i)} className="ml-2">
                            <X size={16} className="text-gray-500 hover:text-red-600" />
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </form>
          </div>

          {/* Fixed Actions at Bottom */}
          <div className="flex justify-end gap-3 pt-3 pb-4 px-5 border-t border-gray-200 bg-gray-50">
            <button
              type="button"
              onClick={onClose}
              className="px-5 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              onClick={handleSubmit}
              className="px-6 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700"
            >
              Create Order
            </button>
          </div>
        </div>
      </PopupAnimation>
    </div>,
    document.body
  );
};

export default CreatePurchaseOrderPopup;