import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { X, ChevronDown, Calendar, Plus, Upload, X as XIcon, Trash2 } from 'lucide-react';
import api from '../../api';
import { PopupAnimation, useAnimationState } from '../../utils/AnimationUtils';
import { useNotification } from '../../components/Notifications';

interface Product {
  id: number;
  name?: string;
  product_name?: string;
  price?: string;
  base_price?: string;
  bdt_price?: number;
}

interface Client {
  id: number;
  company: string;
  contact: string;
}

interface SelectedProduct {
  productId: number;
  productName: string;
  quantity: number;
}

interface CreatePurchaseOrderPopupProps {
  isOpen: boolean;
  onClose: () => void;
  onCreate: (orderData: any) => void;
}

const CreatePurchaseOrderPopup: React.FC<CreatePurchaseOrderPopupProps> = ({
  isOpen,
  onClose,
  onCreate,
}) => {
  const { showError, showInfo } = useNotification();

  const [formData, setFormData] = useState({
    poNumber: '',
    status: 'Draft',
    client: '',
    clientId: 0,
    subscriptionType: '',
    recurringCount: 1,
    deliveryDate: '',
    subscriptionActive: false,
    poDetails: '',
  });

  const [selectedProducts, setSelectedProducts] = useState<SelectedProduct[]>([]);

  const [dropdownStates, setDropdownStates] = useState({
    status: false,
    client: false,
    product: false,
    subscriptionType: false,
  });

  const [currentProductId, setCurrentProductId] = useState<number>(0);
  const [currentQuantity, setCurrentQuantity] = useState<number>(1);

  const [loading, setLoading] = useState(false);
  const [poNumberLoading, setPoNumberLoading] = useState(false);
  const [clients, setClients] = useState<Client[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [attachments, setAttachments] = useState<File[]>([]);

  const statusOptions = ['Draft', 'Active', 'In Progress', 'Completed'];

  const fetchData = async () => {
    setLoading(true);
    try {
      const [clientsResponse, productsResponse] = await Promise.all([
        api.get('/clients'),
        api.get('/products')
      ]);

      setClients(clientsResponse.data);
      setProducts(productsResponse.data);

      fetchAutoGeneratedPoNumber();
    } catch (error) {
      console.error('Error fetching data:', error);
      showError('Failed to load clients or products');
    }
    setLoading(false);
  };

  useEffect(() => {
    if (isOpen) {
      fetchData();
      // Reset form on open
      setSelectedProducts([]);
      setAttachments([]);
    }
  }, [isOpen]);

  const fetchAutoGeneratedPoNumber = async () => {
    setPoNumberLoading(true);
    try {
      const response = await api.get('/purchases/generate-po-number');
      if (response.data && response.data.po_number) {
        setFormData(prev => ({ ...prev, poNumber: response.data.po_number }));
      }
    } catch (error) {
      console.error('Error fetching PO number:', error);
      const year = new Date().getFullYear();
      setFormData(prev => ({ ...prev, poNumber: `PO-${year}-0001` }));
    } finally {
      setPoNumberLoading(false);
    }
  };

  const toggleDropdown = (dropdown: string) => {
    setDropdownStates(prev => ({
      ...prev,
      [dropdown]: !prev[dropdown as keyof typeof prev]
    }));
  };

  const selectClient = (client: Client) => {
    setFormData(prev => ({
      ...prev,
      client: `${client.company} - ${client.contact}`,
      clientId: client.id
    }));
    setDropdownStates(prev => ({ ...prev, client: false }));
  };

  const selectStatus = (status: string) => {
    setFormData(prev => ({ ...prev, status }));
    setDropdownStates(prev => ({ ...prev, status: false }));
  };

  const addProduct = () => {
    if (currentProductId === 0) {
      showInfo('Please select a product');
      return;
    }
    if (currentQuantity < 1) {
      showInfo('Quantity must be at least 1');
      return;
    }

    const product = products.find(p => p.id === currentProductId);
    if (!product) return;

    const existingIndex = selectedProducts.findIndex(p => p.productId === currentProductId);
    if (existingIndex !== -1) {
      // Update quantity if already added
      setSelectedProducts(prev => {
        const updated = [...prev];
        updated[existingIndex].quantity += currentQuantity;
        return updated;
      });
    } else {
      setSelectedProducts(prev => [
        ...prev,
        {
          productId: currentProductId,
          productName: product.product_name || product.name || 'Unknown',
          quantity: currentQuantity
        }
      ]);
    }

    // Reset selectors
    setCurrentProductId(0);
    setCurrentQuantity(1);
    setDropdownStates(prev => ({ ...prev, product: false }));
  };

  const removeProduct = (index: number) => {
    setSelectedProducts(prev => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.clientId) {
      showInfo('Please select a client');
      return;
    }

    if (selectedProducts.length === 0) {
      showInfo('Please add at least one product');
      return;
    }

    if (formData.subscriptionActive) {
      if (!formData.subscriptionType) {
        showInfo('Please select a subscription type');
        return;
      }
      if (!formData.deliveryDate) {
        showInfo('Please select a delivery date');
        return;
      }
      if (formData.recurringCount < 1) {
        showInfo('Recurring count must be at least 1');
        return;
      }
    }

    const formattedData = {
      po_number: formData.poNumber,
      status: formData.status,
      client_id: formData.clientId,
      products: selectedProducts.map(p => ({
        productId: p.productId,
        quantity: p.quantity
      })),
      subscription_type: formData.subscriptionType || null,
      recurring_count: formData.subscriptionType ? formData.recurringCount : null,
      delivery_date: formData.deliveryDate || null,
      subscription_active: formData.subscriptionActive,
      po_details: formData.poDetails || null,
      attachment: attachments.length > 0 ? attachments[0] : null
    };

    onCreate(formattedData);
    handleCancel();
  };

  const handleCancel = () => {
    setFormData({
      poNumber: '',
      status: 'Draft',
      client: '',
      clientId: 0,
      subscriptionType: '',
      recurringCount: 1,
      deliveryDate: '',
      subscriptionActive: false,
      poDetails: '',
    });
    setSelectedProducts([]);
    setCurrentProductId(0);
    setCurrentQuantity(1);
    setAttachments([]);
    onClose();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    const allowedTypes = [
      'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/zip', 'application/x-zip-compressed', 'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'text/plain',
      'image/jpeg', 'image/png', 'image/gif'
    ];

    const validFiles = files.filter(file => {
      if (file.size > 10 * 1024 * 1024) {
        showError(`File ${file.name} is too large (max 10MB)`);
        return false;
      }
      if (!allowedTypes.includes(file.type)) {
        showError(`File type ${file.type} not allowed`);
        return false;
      }
      return true;
    });

    setAttachments(validFiles.slice(0, 5)); // Max 5 files optional
  };

  const removeAttachment = (index: number) => {
    setAttachments(prev => prev.filter((_, i) => i !== index));
  };

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const { isVisible, isAnimating } = useAnimationState(isOpen);
  if (!isOpen && !isAnimating) return null;

  return createPortal(
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[9999]" onClick={onClose}>
      <PopupAnimation animationType="zoomIn" duration="0.3s">
        <div className="bg-white rounded-lg shadow-xl w-full max-w-5xl mx-4 max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
          <div className="flex items-center justify-between p-5 border-b">
            <div>
              <h2 className="text-xl font-bold">Create Purchase Order</h2>
              <p className="text-sm text-gray-500 mt-1">Add client, products, and subscription details</p>
            </div>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X size={24} />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="p-6 space-y-6">
            {/* Basic Info */}
            <div>
              <h3 className="text-lg font-semibold mb-4">Basic Information</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-1">PO Number</label>
                  <input
                    type="text"
                    value={poNumberLoading ? 'Generating...' : formData.poNumber}
                    className="w-full px-3 py-2 border rounded-md bg-gray-50"
                    readOnly
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Status</label>
                  <div className="relative">
                    <button type="button" onClick={() => toggleDropdown('status')} className="w-full px-3 py-2 border rounded-md text-left flex justify-between items-center">
                      {formData.status} <ChevronDown size={16} />
                    </button>
                    {dropdownStates.status && (
                      <div className="absolute z-10 w-full mt-1 bg-white border rounded-md shadow-lg">
                        {statusOptions.map(opt => (
                          <button key={opt} type="button" onClick={() => selectStatus(opt)} className="w-full text-left px-3 py-2 hover:bg-gray-100">
                            {opt}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Client</label>
                  <div className="relative">
                    <button type="button" onClick={() => toggleDropdown('client')} className="w-full px-3 py-2 border rounded-md text-left flex justify-between items-center">
                      {formData.client || 'Select client'} <ChevronDown size={16} />
                    </button>
                    {dropdownStates.client && (
                      <div className="absolute z-10 w-full mt-1 bg-white border rounded-md shadow-lg max-h-60 overflow-auto">
                        {loading ? <div className="p-3 text-center text-gray-500">Loading...</div> : clients.map(client => (
                          <button key={client.id} type="button" onClick={() => selectClient(client)} className="w-full text-left px-3 py-2 hover:bg-gray-100">
                            <div className="font-medium">{client.company}</div>
                            <div className="text-xs text-gray-500">{client.contact}</div>
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>

            {/* Products Section */}
            <div>
              <h3 className="text-lg font-semibold mb-4">Products</h3>

              {/* Add Product Row */}
              <div className="grid grid-cols-1 md:grid-cols-12 gap-3 mb-4 items-end">
                <div className="md:col-span-6">
                  <label className="block text-sm font-medium mb-1">Product</label>
                  <div className="relative">
                    <button type="button" onClick={() => toggleDropdown('product')} className="w-full px-3 py-2 border rounded-md text-left flex justify-between">
                      {products.find(p => p.id === currentProductId)?.product_name || products.find(p => p.id === currentProductId)?.name || 'Select product'}
                      <ChevronDown size={16} />
                    </button>
                    {dropdownStates.product && (
                      <div className="absolute z-10 w-full mt-1 bg-white border rounded-md shadow-lg max-h-60 overflow-auto">
                        {products.map(product => (
                          <button key={product.id} type="button" onClick={() => { setCurrentProductId(product.id); toggleDropdown('product'); }} className="w-full text-left px-3 py-2 hover:bg-gray-100">
                            <div>{product.product_name || product.name}</div>
                            <div className="text-xs text-gray-500">৳{product.bdt_price || product.base_price || product.price}</div>
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
                <div className="md:col-span-3">
                  <label className="block text-sm font-medium mb-1">Quantity</label>
                  <input
                    type="number"
                    min="1"
                    value={currentQuantity}
                    onChange={e => setCurrentQuantity(parseInt(e.target.value) || 1)}
                    className="w-full px-3 py-2 border rounded-md"
                  />
                </div>
                <div className="md:col-span-3">
                  <button type="button" onClick={addProduct} className="w-full px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 flex items-center justify-center gap-2">
                    <Plus size={18} /> Add Product
                  </button>
                </div>
              </div>

              {/* Selected Products List */}
              {selectedProducts.length > 0 && (
                <div className="border rounded-md">
                  <div className="bg-gray-50 px-4 py-2 font-medium text-sm border-b">Selected Products ({selectedProducts.length})</div>
                  <div className="max-h-60 overflow-auto">
                    {selectedProducts.map((item, index) => (
                      <div key={index} className="flex items-center justify-between px-4 py-3 border-b last:border-b-0">
                        <div>
                          <div className="font-medium">{item.productName}</div>
                          <div className="text-sm text-gray-600">Quantity: {item.quantity}</div>
                        </div>
                        <button type="button" onClick={() => removeProduct(index)} className="text-red-600 hover:text-red-800">
                          <Trash2 size={18} />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Subscription & Delivery */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h3 className="text-lg font-semibold mb-4">Subscription</h3>
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      id="subActive"
                      checked={formData.subscriptionActive}
                      onChange={e => setFormData(prev => ({ ...prev, subscriptionActive: e.target.checked }))}
                      className="h-4 w-4"
                    />
                    <label htmlFor="subActive" className="font-medium">Subscription Active</label>
                  </div>

                  {formData.subscriptionActive && (
                    <>
                      <div>
                        <label className="block text-sm font-medium mb-1">Subscription Type</label>
                        <div className="relative">
                          <button type="button" onClick={() => toggleDropdown('subscriptionType')} className="w-full px-3 py-2 border rounded-md text-left flex justify-between">
                            {formData.subscriptionType ? `${formData.subscriptionType} month${formData.subscriptionType !== '1' ? 's' : ''}` : 'Select type'} <ChevronDown size={16} />
                          </button>
                          {dropdownStates.subscriptionType && (
                            <div className="absolute z-10 w-full mt-1 bg-white border rounded-md shadow-lg">
                              {[1, 2, 3, 6, 12].map(m => (
                                <button key={m} type="button" onClick={() => { setFormData(prev => ({ ...prev, subscriptionType: m.toString() })); toggleDropdown('subscriptionType'); }} className="w-full text-left px-3 py-2 hover:bg-gray-100">
                                  {m} month{m > 1 ? 's' : ''}
                                </button>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>

                      <div>
                        <label className="block text-sm font-medium mb-1">Recurring Count</label>
                        <input
                          type="number"
                          min="1"
                          value={formData.recurringCount}
                          onChange={e => setFormData(prev => ({ ...prev, recurringCount: parseInt(e.target.value) || 1 }))}
                          className="w-full px-3 py-2 border rounded-md"
                        />
                      </div>
                    </>
                  )}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Delivery Date {formData.subscriptionActive && '(Required)'}</label>
                <div className="relative">
                  <input
                    type="date"
                    value={formData.deliveryDate}
                    onChange={e => setFormData(prev => ({ ...prev, deliveryDate: e.target.value }))}
                    className="w-full px-3 py-2 border rounded-md"
                  />
                  {/* <Calendar className="absolute right-3 top-2.5 text-gray-400" size={20} /> */}
                </div>
              </div>
            </div>

            {/* PO Details & Attachments */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium mb-1">PO Details (Optional)</label>
                <textarea
                  rows={4}
                  value={formData.poDetails}
                  onChange={e => setFormData(prev => ({ ...prev, poDetails: e.target.value }))}
                  className="w-full px-3 py-2 border rounded-md"
                  placeholder="Additional notes or details..."
                />
              </div>

              <div>
                <h3 className="text-lg font-semibold mb-3">Attachments</h3>
                <div className="border-2 border-dashed rounded-lg p-6 text-center">
                  <Upload className="mx-auto text-gray-400 mb-3" size={40} />
                  <label className="cursor-pointer text-blue-600 hover:text-blue-700">
                    <span className="font-medium">Click to upload</span> or drag and drop
                    <input type="file" multiple className="hidden" onChange={handleFileChange} accept=".pdf,.doc,.docx,.zip,.xls,.xlsx,.txt,.jpg,.jpeg,.png,.gif" />
                  </label>
                  <p className="text-xs text-gray-500 mt-2">Max 10MB per file</p>
                </div>

                {attachments.length > 0 && (
                  <div className="mt-4 space-y-2">
                    {attachments.map((file, i) => (
                      <div key={i} className="flex items-center justify-between bg-gray-50 p-3 rounded">
                        <div>
                          <p className="text-sm font-medium">{file.name}</p>
                          <p className="text-xs text-gray-500">{formatFileSize(file.size)}</p>
                        </div>
                        <button type="button" onClick={() => removeAttachment(i)}>
                          <XIcon size={18} className="text-gray-500 hover:text-red-600" />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Actions */}
            <div className="flex justify-end gap-3 pt-4 border-t">
              <button type="button" onClick={handleCancel} className="px-6 py-2 border rounded-md hover:bg-gray-50">
                Cancel
              </button>
              <button type="submit" className="px-6 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800">
                Create Purchase Order
              </button>
            </div>
          </form>
        </div>
      </PopupAnimation>
    </div>,
    document.body
  );
};

export default CreatePurchaseOrderPopup;